name: unit_converter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/regular_units.json

    - assets/icons/area.png
    - assets/icons/currency.png
    - assets/icons/digital_storage.png
    - assets/icons/energy.png
    - assets/icons/length.png
    - assets/icons/mass.png
    - assets/icons/time.png
    - assets/icons/volume.png

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Light.ttf
        # - asset: assets/fonts/Raleway-Light.ttf
        #   weight: 300